[package]
name = "geekp"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.2.1"

[[bin]]
name = "chapter_1"
path = "src/chapter_1.rs"

[[bin]]
name = "chapter_2"
path = "src/chapter_2.rs"

[[bin]]
name = "chapter_3"
path = "src/chapter_3/main.rs"
